name: Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Publish Gradle Plugin
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Setup Gradle Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set Version Environment Variable
      run: |
        export NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
    - name: Publish Gradle Plugin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build publish -Pversion=${{ env.NEW_VERSION }} --info
